from dataclasses import dataclass

from xno.data2.fundamental.entity.base import StockEntity


@dataclass
class BalanceSheet(StockEntity):
    _DATAFRAME_MAPPING = {
        "ticker": "ticker",
        "yearReport": "year_report",
        "lengthReport": "length_report",
        "CURRENT ASSETS (Bn. VND)": "current_assets",
        "Cash and cash equivalents (Bn. VND)": "cash_and_cash_equivalents",
        "Short-term investments (Bn. VND)": "short_term_investments",
        "Accounts receivable (Bn. VND)": "accounts_receivable",
        "Net Inventories": "net_inventories",
        "Other current assets": "other_current_assets",
        "LONG-TERM ASSETS (Bn. VND)": "long_term_assets",
        "Fixed assets (Bn. VND)": "fixed_assets",
        "Long-term investments (Bn. VND)": "long_term_investments",
        "Other non-current assets": "other_non_current_assets",
        "TOTAL ASSETS (Bn. VND)": "total_assets",
        "LIABILITIES (Bn. VND)": "liabilities",
        "Current liabilities (Bn. VND)": "current_liabilities",
        "Long-term liabilities (Bn. VND)": "long_term_liabilities",
        "OWNER'S EQUITY(Bn.VND)": "owners_equity",
        "Capital and reserves (Bn. VND)": "capital_and_reserves",
        "Other Reserves": "other_reserves",
        "Undistributed earnings (Bn. VND)": "undistributed_earnings",
        "TOTAL RESOURCES (Bn. VND)": "total_resources",
        "Prepayments to suppliers (Bn. VND)": "prepayments_to_suppliers",
        "Inventories, Net (Bn. VND)": "inventories_net",
        "Other current assets (Bn. VND)": "other_current_assets",
        "Common shares (Bn. VND)": "common_shares",
        "Paid-in capital (Bn. VND)": "paid_in_capital",
        "Long-term borrowings (Bn. VND)": "long_term_borrowings",
        "Advances from customers (Bn. VND)": "advances_from_customers",
        "Short-term borrowings (Bn. VND)": "short_term_borrowings",
        "Long-term prepayments (Bn. VND)": "long_term_prepayments",
        "Other long-term assets (Bn. VND)": "other_long_term_assets",
        "MINORITY INTERESTS": "minority_interests",
        "Long-term trade receivables (Bn. VND)": "long_term_trade_receivables",
        "Minority Interest": "minority_interest",
        "Goodwill": "goodwill",
        "Balances with the SBV": "balances_with_the_sbv",
        "Placements with and loans to other credit institutions": "placements_with_and_loans_to_other_credit_institutions",
        "Trading Securities, net": "trading_securities_net",
        "Trading Securities": "trading_securities",
        "Provision for diminution in value of Trading Securities": "provision_for_diminution_in_value_of_trading_securities",
        "Derivatives and other financial liabilities": "derivatives_and_other_financial_liabilities",
        "Loans and advances to customers, net": "loans_and_advances_to_customers_net",
        "Loans and advances to customers": "loans_and_advances_to_customers",
        "Less: Provision for losses on loans and advances to customers": "less_provision_for_losses_on_loans_and_advances_to_customers",
        "Investment Securities": "investment_securities",
        "Available-for Sales Securities": "available_for_sales_securities",
        "Held-to-Maturity Securities": "held_to_maturity_securities",
        "Less: Provision for diminution in value of investment securities": "less_provision_for_diminution_in_value_of_investment_securities",
        "Investments in associate companies": "investments_in_associate_companies",
        "Less: Provision for diminuation in value of long term investments": "less_provision_for_diminuation_in_value_of_long_term_investments",
        "Tangible fixed assets": "tangible_fixed_assets",
        "Intagible fixed assets": "intagible_fixed_assets",
        "Investment in properties": "investment_in_properties",
        "Other Assets": "other_assets",
        "Due to Gov and borrowings from SBV": "due_to_gov_and_borrowings_from_sbv",
        "Deposits and borrowings from other credit institutions": "deposits_and_borrowings_from_other_credit_institutions",
        "Deposits from customers": "deposits_from_customers",
        "_Derivatives and other financial liabilities": "derivatives_and_other_financial_liabilities",
        "Funds received from Gov, international and other institutions": "funds_received_from_gov_international_and_other_institutions",
        "Convertible bonds/CDs and other valuable papers issued": "convertible_bonds_cds_and_other_valuable_papers_issued",
        "Other liabilities": "other_liabilities",
        "Capital": "capital",
        "Reserves": "reserves",
        "Foreign Currency Difference reserve": "foreign_currency_difference_reserve",
    }
